module;
#include <time.h>

module Dumper;

// Imports
//------------------------------------------------------------------------
import Console;
import Logger;
import Memory;
import Arguments;

import <chrono>;
import <fstream>;
import <thread>;
import <sstream>;
import <print>;
import <filesystem>;
import <iostream>;

import <Windows.h>;

using namespace ALIM;

// Helper Functions
//------------------------------------------------------------------------
static std::string GetTimeFormatted() {
    using namespace std::chrono;
    const system_clock::time_point Now = system_clock::now();
    const std::time_t Time = system_clock::to_time_t(Now);

    std::tm TimeInfo = {};
    localtime_s(&TimeInfo, &Time);

    char TimeString[20];
    std::strftime(TimeString, sizeof(TimeString), "%d/%m/%Y %H:%M:%S", &TimeInfo);

    return std::string(TimeString);
}

std::string EscapeString(const std::string& Input) {
    std::string Escaped;
    for (size_t i = 0; i < Input.length(); i++) {
        if (Input[i] == '\\' && i + 1 < Input.length() && Input[i + 1] == 'x') {
            if (i + 3 < Input.length()) {
                // Extract the hex value (2 characters) and convert it to an integer
                std::string hexValue = Input.substr(i + 2, 2);
                char escapedChar = static_cast<char>(std::stoi(hexValue, 0, 16));

                // Append the escaped charactre to the result string
                Escaped += escapedChar;

                // Skip
                i += 3;
            } else {
                // If there are not enough characters for a valid escape sequence, just add the '\\x' as-is
                Escaped += "\\x";
            }
        } else {
            Escaped += Input[i];
        }
    }

    return Escaped;
}

// TODO: Make safe...
static std::string ReplaceSignature(const std::string& Line) {
    std::string Result = Line;
    std::size_t StartPos = Result.find("_SIG(");

    while (StartPos != std::string::npos) {
        std::size_t EndPos = Result.find(")", StartPos);

        if (EndPos != std::string::npos) {
            std::string SigCall = Result.substr(StartPos, EndPos - StartPos + 1);
            std::string Pattern, Mask = "";

            std::size_t CommaPos = SigCall.find(",");
            if (CommaPos != std::string::npos) {
                Pattern = SigCall.substr(0, CommaPos);
                Pattern = Pattern.substr(6, Pattern.size() - 7);

                Mask = SigCall.substr(CommaPos + 1);
                Mask = Mask.substr(2, Mask.size() - 4);

                auto EscapedPattern = EscapeString(Pattern);
                auto Sig = Memory::Signature(EscapedPattern, Mask);
                const uint32_t Offset = Memory::FindPattern(Sig);
                if (!Offset) {
                    ALIM_CORE_ERROR("Failed getting:\nPattern: {}\nMask: {}", Pattern, Mask);
                    Result.replace(StartPos, EndPos - StartPos + 1, "0x0");
                } else {
                    Result.replace(StartPos, EndPos - StartPos + 1, std::format("{:#x}", Offset));
                }
            }

            StartPos = Result.find("_SIG(", StartPos + 1);
        } else {
            StartPos = Result.find("_SIG(", StartPos + 1);
        }
    }

    return Result;
}

// Dumper Functions
//------------------------------------------------------------------------
void Dumper::Dump() {
    std::ifstream Signatures("DATA/ALIM/INTERNAL/SIGNATURES");
    if (!Signatures.is_open()) {
        MessageBoxW(nullptr, L"Unable to open \"DATA/ALIM/INTERNAL/SIGNATURES\"", L"ALIM-Core Dumper", MB_OK | MB_ICONERROR);
    }

    std::string Line;
    std::stringstream OutBuffer;
    OutBuffer << "//------------------------------------------------------------------------\n"
              << "// Generated by Dumper.cpp\n"
              << "// Date: " << GetTimeFormatted() << "\n"
              << "//------------------------------------------------------------------------\n";

    while (std::getline(Signatures, Line)) {
        OutBuffer << ReplaceSignature(Line) << '\n';
    }

    auto OutString = OutBuffer.str();

    if (Arg::GetCommandLineOption("dump-to-clipboard")) {
        auto GlobalMem = GlobalAlloc(GMEM_FIXED, OutString.size());
        memcpy(GlobalMem, OutString.data(), OutString.size());
        
        OpenClipboard(nullptr);
        EmptyClipboard();
        SetClipboardData(CF_TEXT, GlobalMem);
        CloseClipboard();
    
        ALIM_CORE_INFO("Dumped Offsets to Clipboard!");
    } else { // Default
        std::string Filepath = Arg::GetCommandLineVar<std::string>("dump-path");

        namespace fs = std::filesystem;

        fs::path CompletePath;
        
        if (!Filepath.empty() && fs::path(Filepath).has_parent_path()) {
            if (fs::is_directory(Filepath)) { // If we just specified a directory
                CompletePath = fs::path(Filepath) / "Offsets.ixx";
            } else { // Directory + File
                CompletePath = Filepath;
            }
        } else {
            std::string DefaultDir = Arg::GetCommandLineVar<std::string>("launch-dir");
            if (!DefaultDir.empty()) {
                DefaultDir = fs::path(DefaultDir).string();
            }
        
            CompletePath = fs::path(DefaultDir) / "Offsets.ixx";
        }
        
        std::ofstream Outfile(CompletePath.string(), std::ios::out | std::ios::trunc);
        Outfile << OutString;
        Outfile.close();

        ALIM_CORE_INFO("Dumped to {}", CompletePath.string());
    }
}